language: python
cache: pip
sudo: false

matrix:
  include:
   - env: TOXENV=py34
     python: 3.4
   - env: TOXENV=py35
     python: 3.5
   - env: TOXENV=py36
     python: 3.6

# Package installation
install:
  - pip install tox coveralls scrutinizer-ocular

# Run the tests
script:
  tox

after_success:
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
