[pytest]
python_paths = testproject/
DJANGO_SETTINGS_MODULE = testproject.settings
django_find_project = false
python_files = tests.py test_*.py *_tests.py
norecursedirs = venv* .*
addopts =
    -r fEsxXw
    -vvv
    --doctest-modules
    --ignore setup.py
    --cov-report=term-missing
    --cov=meeting
    tests/
